name: Test with Coverage

on:
  push:
    branches:
      - 'dev/**'
  pull_request:
    branches:
      - main # main 브랜치로 들어오는 PR에 대해 실행

permissions:
  contents: read
  pull-requests: write # PR에 코멘트를 작성하기 위한 권한 추가

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.2

      - name: Run tests and generate JaCoCo report
        id: test
        run: ./gradlew clean test

      - name: Upload Test Report on Failure
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ github.run_id }}
          path: build/reports/tests/test/
          retention-days: 7

      - name: Add JaCoCo report to PR comment
        if: github.event_name == 'pull_request'
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80 # 전체 커버리지 최소 기준 (예시)
          min-coverage-changed-files: 90 # 변경된 파일의 커버리지 최소 기준 (예시)
          title: '📝 Code Coverage'